# https://docs.docker.com/compose

version: '3'
services:
  # webapp:
  #   build: .
  #   depends_on:
  #     - db

  db:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER?}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD?}
    ports:
      - ${DB_PORT}:${DB_PORT}
